openapi: 3.0.0
info:
  title: REST API Compulsory Assignment
  description: MEN (MongoDB - ExpressJS - NodeJS) REST API
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/
tags:
- name: "actor"
  description: "Everything related to actors"
- name: "movie"
  description: "Everything related to movies"
- name: "user"
  description: "Operations related to the user"
paths:
  /actors/:
    get:
      tags:
      - "actor"
      summary: "retrieves all actors"
      description: ""
      operationId: "getAllActors"
      produces:
      - "application/json"
      - "application/xml"
      responses:
        200:
          description: "success"
          schema:
            type: "array"
            items:
              $ref: "#/components/schemas/Actor"
        400:
          description: "Invalid"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: auth-token
  schemas:
    Actor:
      type: object
      required:
        - firstName
        - lastName
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        yearOfBirth:
          type: number
        awards: 
          type: array
          items:
            type: string
    Movie:
      type: object
      required:
        - title
      properties:
        id:
          type: string
        title:
          type: string
        genre:
          type: string
        description: 
          type: string
        director: 
          type: string
        yearOfRelease:
          type: number
        cast:
          type: array
          items:
            $ref: '#/components/schemas/Actor'
    User:
      type: object
      required:
        - username
        - email
        - password
      properties:
        firstName:
          type: string
          minLength: 2
          maxLength: 200
        lastName:
          type: string
          minLength: 2
          maxLength: 200
        username:
          type: string
          minLength: 6
          maxLength: 25
        email:
          type: string
        password:
          type: string
          minLength: 8
          maxLength: 128
        dateCreated:
          type: string
          format: date-time